openapi: 3.0.1
info:
  title: MaximNBNOrderDetailInboundService
  description: API Definition of MaximNBNOrderDetailInboundService
  version: 1.0.0
servers:
- url: http://localhost:8290/application/maxim/v1/order-details
paths:
  /:
    get:
      responses:
        default:
          description: Default response
