openapi: 3.0.1
info:
  title: NBNOrderDetailsInboundServiceAPI
  description: API Definition of NBNOrderDetailsInboundServiceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/ratelimit
paths:
  /:
    get:
      responses:
        default:
          description: Default response
